site_name: Euro Calliope
nav:
    - Home: index.md
    - Use pre-builts: pre-built.md
    - Use your own builds: build.md
    - Model: model.md
    - Customisation: customisation.md
    - Release notes: changelog.md
    - Sources: sources.md
theme: readthedocs
repo_url: https://github.com/calliope-project/euro-calliope/
site_dir: build/docs
markdown_extensions:
    - admonition
    - toc:
        permalink: "#"
