$schema: http://json-schema.org/draft-07/schema#
description: Euro-Calliope configuration schema
properties:
    data-sources:
        type: object
        properties:
            biofuel-potentials:
                type: string
                pattern: .*{feedstock}.*\.csv$
                description: Path to local biofuel potentials. Must contain {feedstock} placeholder.
            biofuel-costs:
                type: string
                pattern: .*{feedstock}.*\.csv$
                description: Path to local cost data. Must contain {feedstock} placeholder.
            eez:
                type: string
                description: Path to local geospatial Exclusive Economic Zones data.
            irena-generation:
                type: string
                pattern: .*\.csv$
                description: Path to local hydro generation data from IRENA.
            national-phs-storage-capacities:
                type: string
                pattern: .*\.csv$
                description: Path to local storage capacities data (in GWh).
            capacity-factors:
                type: string
                pattern: ^(https?|http?):\/\/.+{filename}.*
                description: Web address of the capacity factor timeseries. Must contain {filename} placeholder.
            gadm:
                type: string
                pattern: ^(https?|http?):\/\/.+{country_code}.*
                description: Web address of geospatial GADM data. Must contain {country_code} placeholder.
            hydro-basins:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of geospatial basins data.
            hydro-stations:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of database of hydro stations.
            load:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of load data.
            nuts:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of geospatial NUTS data.
            potentials:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of potentials of solar and wind.
    root-directory:
        type: string
        description: Path to the root directory of euro-calliope containing scripts and template folders.
    cluster-sync:
        type: object
        properties:
            url:
                type: string
                description: URL of the cluster.
            send-ignore:
                type: string
                description: Path to local file defining files and folders to ignore when sending to cluster (relative to workdir).
            receive-ignore:
                type: string
                description: Path to local file defining files and folders to ignore when receiving from cluster (relative to workdir).
            cluster-base-dir:
                type: string
                description: Path on cluster into which files are sent from local machine (must exist).
            local-results-dir:
                type: string
                description: Path to local folder into which results from cluster are downloaded (relative to workdir).
    quality-control:
        type: object
        properties:
            load:
                type: object
                properties:
                    acceptable-year-diff-for-gap-filling:
                        type: integer
                        description: When filling data gaps in electricity load data, this specifies the absolute number of years from the current year that the model can use data for filling. A value of zero effectively removes this gap filling method.
                    outlier-data-thresholds:
                        type: object
                        properties:
                            relative-to-mean-min:
                                type: number
                                description: lower bound cut-off value for any hourly data relative to the annual mean load of a country. Any values below this lower bound will be replaced by interpolated values.
                            relative-to-mean-max:
                                type: number
                                description: upper bound cut-off value for any hourly data relative to the annual mean load of a country. Any values above this upper bound will be replaced by interpolated values.
                            percentage-deviation-post-cleaning-max:
                                type: number
                                description: allowable deviation in annual load for any country following removal and subsequent interpolation of outlier data.
                    entsoe-data-priority:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                            type: string
                            enum: [actual_entsoe_power_statistics, actual_entsoe_transparency, actual_tso, actual_net_consumption_tso, actual_gross_generation_tso, forecast_entsoe_transparency, forecast_tso]
                        description: Order in which to prioritise available electricity load data from open-power-system-data.org. The first source in the list will be used to initialise the data; the remaining data sources in the list will be use to gap fill in order from first to last.
                    interpolate-hours:
                        type: integer
                        description: maximum number of hours over which missing load data can be interpolated.
                    fill-29th-feb-from-28th:
                        type: boolean
                        description: Whether or not to gap-fill empty 29th of February data for leap years with data from the day before.
            hydro:
                type: object
                properties:
                    scale-phs-according-to-geth-et-al:
                        type: boolean
                        description: Whether or not to use pumped hydro capacities derived from Geth et al. (2015) to scale pumped hydro capacities givven by the JRC hydro database.
