$schema: http://json-schema.org/draft-07/schema#
description: Euro-Calliope configuration schema
properties:
    data-sources:
        type: object
        properties:
            biofuel-potentials:
                type: string
                pattern: .*{feedstock}.*\.csv$
                description: Path to local biofuel potentials. Must contain {feedstock} placeholder.
            biofuel-costs:
                type: string
                pattern: .*{feedstock}.*\.csv$
                description: Path to local cost data. Must contain {feedstock} placeholder.
            eez:
                type: string
                description: Path to local geospatial Exclusive Economic Zones data.
            hydro-basins:
                type: string
                description: Path to local geospatial basins data.
            irena-generation:
                type: string
                pattern: .*\.csv$
                description: Path to local hydro generation data from IRENA.
            national-phs-storage-capacities:
                type: string
                pattern: .*\.csv$
                description: Path to local storage capacities data (in GWh).
            capacity-factors:
                type: string
                pattern: ^(https?|http?):\/\/.+{filename}.*
                description: Web address of the capacity factor timeseries. Must contain {filename} placeholder.
            gadm:
                type: string
                pattern: ^(https?|http?):\/\/.+{country_code}.*
                description: Web address of geospatial GADM data. Must contain {country_code} placeholder.
            hydro-stations:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of database of hydro stations.
            load:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of load data.
            nuts:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of geospatial NUTS data.
            potentials:
                type: string
                pattern: ^(https?|http?):\/\/.+
                description: Web address of potentials of solar and wind.
    root-directory:
        type: string
        description: Path to the root directory of euro-calliope containing scripts and template folders.
    parameters:
        type: object
        properties:
            entsoe-data-priority:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                    type: string
                    enum: [actual_entsoe_power_statistics, actual_entsoe_transparency, actual_tso, actual_net_consumption_tso, actual_gross_generation_tso, forecast_entsoe_transparency, forecast_tso]
                description: Order in which to prioritise available electricity load data from open-power-system-data.org. The first source in the list will be used to initialise the data; the remaining data sources in the list will be use to gap fill in order from first to last.
