name: default
channels:
    - conda-forge
dependencies:
    - python=3.7
    - ipython
    - numpy=1.18.5
    - pandas=1.0.5
    - pycountry=19.8.18
    - jinja2
    - pip=21.0.1
    - pip:
        - -e ../../lib[geo]
