name: euro-calliope
channels:
    - conda-forge
    - gurobi
dependencies:
    - python=3.8
    - numpy=1.20.2
    - pandas=1.1.5
    - xarray=0.16.2
    - gurobi=9.1.2
    - calliope=0.6.6.post1
    - pyomo=5.7.3
    - pyutilib=6.0.0
